dataframe_order = ['name',
        'abbreviation',
        'rank',
        'EWP',
        'W',
        'L',
        'GP',
        'PW',
        'PL',
        'Ahead/Behind',
        'PW Season',
        'PL Season',
        'points',
        'opp_points',
        'Point Diff',
        'assists', 
        'opp_assists', 
        'Assist Diff',
        'blocks',
        'opp_blocks',
        'Block Diff',
        'defensive_rebounds',
        'opp_defensive_rebounds',
        'Def Reb Diff',
        'field_goal_attempts', 
        'opp_field_goal_attempts',
        'FG Att Diff',
        'field_goal_percentage', 
        'field_goals',
        'opp_field_goals',
        'FG Diff',
        'free_throw_attempts',
        'opp_free_throw_attempts',
        'FT Att Diff',
        'free_throw_percentage', 
        'free_throws',
        'opp_free_throws',
        'FT Diff',
        'games_played', 
        'minutes_played', 
        'offensive_rebounds',
        'opp_offensive_rebounds',
        'Off Reb Diff',
        'opp_field_goal_percentage',
        'opp_free_throw_percentage',
        'personal_fouls',
        'opp_personal_fouls',
        'Personal Foul Diff',
        'steals',
        'opp_steals', 
        'Steal Diff',
        'three_point_field_goal_attempts',
        'opp_three_point_field_goal_attempts',
        '3pt Att Diff',
        'opp_three_point_field_goal_percentage', 
        'three_point_field_goals',
        'opp_three_point_field_goals',
        '3pt FG Diff',
        'total_rebounds',
        'opp_total_rebounds', 
        'Rebound Diff',
        'turnovers',
        'opp_turnovers',
        'Turnover Diff',
        'two_point_field_goal_attempts',
        'opp_two_point_field_goal_attempts',
        '2pt FG Att Diff',
        'two_point_field_goals',
        'opp_two_point_field_goals',
        '2pt FG Diff',
        'opp_two_point_field_goal_percentage',
        'three_point_field_goal_percentage',
        'two_point_field_goal_percentage'
        ]

r2List = ['name',
        'abbreviation',
        'rank',
        'W',
        'EWP',
        'L',
        'GP',
        'PW',
        'PL',
        'Ahead/Behind',
        'PW Season',
        'PL Season',
        'points',
        'opp_points',
        'Point Diff',
        'assists', 
        'opp_assists', 
        'Assist Diff',
        'blocks',
        'opp_blocks',
        'Block Diff',
        'defensive_rebounds',
        'opp_defensive_rebounds',
        'Def Reb Diff',
        'field_goal_attempts', 
        'opp_field_goal_attempts',
        'FG Att Diff',
        'field_goal_percentage', 
        'field_goals',
        'opp_field_goals',
        'FG Diff',
        'free_throw_attempts',
        'opp_free_throw_attempts',
        'FT Att Diff',
        'free_throw_percentage', 
        'free_throws',
        'opp_free_throws',
        'FT Diff',
        'games_played', 
        'minutes_played', 
        'offensive_rebounds',
        'opp_offensive_rebounds',
        'Off Reb Diff',
        'opp_field_goal_percentage',
        'opp_free_throw_percentage',
        'personal_fouls',
        'opp_personal_fouls',
        'Personal Foul Diff',
        'steals',
        'opp_steals', 
        'Steal Diff',
        'three_point_field_goal_attempts',
        'opp_three_point_field_goal_attempts',
        '3pt Att Diff',
        'opp_three_point_field_goal_percentage', 
        'three_point_field_goals',
        'opp_three_point_field_goals',
        '3pt FG Diff',
        'total_rebounds',
        'opp_total_rebounds', 
        'Rebound Diff',
        'turnovers',
        'opp_turnovers',
        'Turnover Diff',
        'two_point_field_goal_attempts',
        'opp_two_point_field_goal_attempts',
        '2pt FG Att Diff',
        'two_point_field_goals',
        'opp_two_point_field_goals',
        '2pt FG Diff',
        'opp_two_point_field_goal_percentage',
        'three_point_field_goal_percentage',
        'two_point_field_goal_percentage']