cols = ['name','year','and_ones','team_abbreviation','assist_percentage', 
        'assists', 'assists_per_poss', 
        'block_percentage', 'blocking_fouls', 'blocks', 'blocks_per_poss', 
        'box_plus_minus', 'center_percentage', 'defensive_box_plus_minus', 
        'defensive_rebound_percentage', 'defensive_rebounds', 
        'defensive_rebounds_per_poss', 'defensive_win_shares', 'dunks', 
        'effective_field_goal_percentage', 'field_goal_attempts', 
        'field_goal_attempts_per_poss', 
        'field_goal_perc_sixteen_foot_plus_two_pointers', 
        'field_goal_perc_ten_to_sixteen_feet', 
        'field_goal_perc_three_to_ten_feet', 
        'field_goal_perc_zero_to_three_feet', 'field_goal_percentage', 
        'field_goals', 'field_goals_per_poss', 'free_throw_attempt_rate', 
        'free_throw_attempts', 'free_throw_attempts_per_poss', 
        'free_throw_percentage', 'free_throws', 'free_throws_per_poss', 
        'games_played', 'games_started', 'half_court_heaves', 
        'half_court_heaves_made', 'height', 'lost_ball_turnovers', 
        'minutes_played', 'nationality', 'net_plus_minus', 
        'offensive_box_plus_minus', 'offensive_fouls', 
        'offensive_rebound_percentage', 'offensive_rebounds', 
        'offensive_rebounds_per_poss', 'offensive_win_shares', 
        'on_court_plus_minus', 'other_turnovers', 'passing_turnovers', 
        'percentage_field_goals_as_dunks', 
        'percentage_of_three_pointers_from_corner', 
        'percentage_shots_three_pointers', 'percentage_shots_two_pointers', 
        'percentage_sixteen_foot_plus_two_pointers', 
        'percentage_ten_to_sixteen_footers', 'percentage_three_to_ten_footers', 
        'percentage_zero_to_three_footers', 'personal_fouls', 
        'personal_fouls_per_poss', 'player_efficiency_rating', 
        'point_guard_percentage', 'points', 'points_per_poss', 
        'points_generated_by_assists', 'position', 'power_forward_percentage', 
        'salary', 'shooting_distance', 'shooting_fouls', 'shooting_fouls_drawn', 
        'shooting_guard_percentage', 'shots_blocked', 'small_forward_percentage', 
        'steal_percentage', 'steals', 'steals_per_poss', 'take_fouls', 
        'three_point_attempt_rate', 'three_point_attempts', 
        'three_point_attempts_per_poss', 'three_point_percentage', 
        'three_point_shot_percentage_from_corner', 'three_pointers', 
        'three_pointers_assisted_percentage', 'three_pointers_per_poss', 
        'total_rebound_percentage', 'total_rebounds', 'total_rebounds_per_poss', 
        'true_shooting_percentage', 'turnover_percentage', 'turnovers', 
        'turnovers_per_poss', 'two_point_attempts', 'two_point_attempts_per_poss', 
        'two_point_percentage', 'two_pointers', 'two_pointers_per_poss', 
        'two_pointers_assisted_percentage', 
        'usage_percentage', 'value_over_replacement_player', 'weight', 
        'win_shares', 'win_shares_per_48_minutes']
